name: panache
description: Flutter Material Theme editor
version: 0.2.2
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/panache

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^1.0.1
  string_scanner: any
  google_sign_in: ^3.2.4
  googleapis: ^0.52.0+1
  shared_preferences: ^0.5.3

  panache_core:
    path: ../panache_core
  panache_ui:
    path: ../panache_ui
  panache_services:
    path: ../panache_services

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any

flutter:
  uses-material-design: true
  assets:
    - assets/google.png
    - assets/google-drive.png
    - packages/panache_core/logo.png
