name: panache_desktop
description: panache on desktop

version: 0.2.2
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/panache

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^1.0.1
  string_scanner: any

  shared_preferences: ^0.5.3
  shared_preferences_fde:
    path: ../desktop_plugins/shared_preferences_fde

  path_provider: ^1.3.0
  path_provider_fde:
    path: ../desktop_plugins/path_provider_fde

  panache_core:
    path: ../panache_core
  panache_ui:
    path: ../panache_ui
  panache_services:
    path: ../panache_services

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any

flutter:
  uses-material-design: true
  assets:
    - packages/panache_core/logo.png
