name: panache_ui
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  panache_core:
    path: ../panache_core

  provider: ^3.1.0

  #panache_services:
    #path: ../panache_services

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - github.png
