name: panache_web
description: panache for the web
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"  

dependencies:
  shared_preferences: 2.0.5 
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  scoped_model: ^2.0.0-nullsafety.0
  provider: ^5.0.0 
  js: ^0.6.3

  panache_core:
    path: ../panache_core

  panache_ui:
    path: ../panache_ui

flutter:
  uses-material-design: true
